MAX_LENGTH_NAME_TAG = 32
MAX_LENGTH_SLUG = 32
MAX_LENGTH_NAME_INGREDIENT = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_NAME_RECIPE = 256
MAX_LENGTH_SHORT_LINK = 10

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
